### ISSUE TITLE
Feature/Client - Show password feature login

### ISSUE THREAD

**Issue by podiman** [code-mentoring/learn#275]
## The story:
As a **user** that **wants to login to the site**, I want to **see the password that they typed**

---

## What we should do:
We should **build a show password field in login form** so that **user can look at the password typed before confirming**.

---

## To be successful we need to:
- [ ] Show password icon in password field
- [ ] On click show plain text password
- [ ] Click again, turn back to original state

---

## Design
![image](https://user-images.githubusercontent.com/3611890/87875453-51592080-c99f-11ea-89c2-60269ab83529.png)

[LINK TO FIGMA DESIGN](https://www.figma.com/file/eyk5tQgLhIpyiORYfWxeUh/Learning-App?node-id=1655%3A140)

---

**Comment by TomoyaKuroda** [comment]
@tristanMatthias 
The icon conflicts with the LastPass icon as below, I think it's not a good idea to place the icon there because many users install the LastPass extension.
![2020-07-25 154217](https://user-images.githubusercontent.com/31934952/88465176-e02dd780-ce8e-11ea-806e-e327921090af.png)

Is it ok to move the password icon to the area under the password input field and replace it with the text "Show password" ?
![87875453-51592080-c99f-11ea-89c2-60269ab83529](https://user-images.githubusercontent.com/31934952/88465161-bc6a9180-ce8e-11ea-8d96-1c65a3c4bfce.png)
